### Practice Questions on NumPy 

In [ ]:
import numpy as np

**Q1)**

Given the list of absolute magnitudes of the stars, calculate its mean and standard deviation using NumPy.

```
abs_mag = [-11.2, 10.3, 1.1, 8.9, -2, 6.3]
```

In [ ]:
# Given list of abs_mag
abs_mag = [-11.2, 10.3, 1.1, 8.9, -2, 6.3]

# Create array from the list


# Print mean and std of the array
print()
print()

In [ ]:
# Soln

# Given list
abs_mag = [-11.2, 10.3, 1.1, 8.9, -2, 6.3]

# Create array of abs_mag_arr from abs_mag list
abs_mag_arr = np.array(abs_mag)

# Print mean and std correct to 3dp for the abs_mag_arr
print(f'Mean of abs_mag:- {round(abs_mag_arr.mean(), 3)}')
print(f'Standard Deviation of abs_mag:- {round(abs_mag_arr.std(),3)}')

Mean of abs_mag:- 2.233
Standard Deviation of abs_mag:- 7.368


**Q2)**      

1. Create random array of integers between 1 and 10 (both inclusive) of size (3, 3).
2. Set a seed value of 42 before creating random array.
3. Reshape this array into 1D array of 9 elements.
4. Print the dimensions of the reshaped array. It should be 1.

In [ ]:
# Write your solution here





In [ ]:
# Soln

# Setting seed value of 42 to initiate same randomness for everyone
np.random.seed(42)

# Create array of random integers between 1 to 10 (inclusive) of shape 3x3
rand_int_arr = np.random.randint(low=0, high=11, size=(3,3))
print('Random Integers between 1 to 10 Array of Shape 3x3:- ')
print(rand_int_arr)

# Reshape it into 1D array of size 9
print()
reshaped_output = rand_int_arr.reshape(9)
print('Reshaped array into 1D:-')
print(reshaped_output)
print(f'\nThere are {reshaped_output.ndim} dimensions in the reshaped_output array!')

Random Integers between 1 to 10 Array of Shape 3x3:- 
[[ 6  3 10]
 [ 7  4  6]
 [ 9  2  6]]

Reshaped array into 1D:-
[ 6  3 10  7  4  6  9  2  6]

There are 1 dimensions in the reshaped_output array!


**Q3)**

1. Create any 2D array using `np.arange` of shape `3x3`.
2. Create one more 2D array using `np.full` of shape `3x4` using value of 2.
3. Perform matrix multiplication on these arrays using `@` operator.

In [ ]:
# Create a 2D array of your choice using np.arange of shape 3x3


# Create a 2D array using np.full with all values to be 2 of shape 3x4


# Perform matrix multiplication using @ operator




In [ ]:
# Soln

# 2D array using np.arange of shape 3x3
arr_2d = np.arange(start=1,stop=10).reshape(3,3)
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# 2D array using np.full of shape 3x4 with values 2
another_arr_2d = np.full(shape=(3,4), fill_value=2)
print(another_arr_2d)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [ ]:
# Matrix multiplication (3x3) @ (3x4) ---> (3x4)
matrix_multiplication_output = arr_2d@another_arr_2d
print(f'Matrix Multiplication of\n{arr_2d}\n\nand\n{another_arr_2d}\n\nis:-\n{matrix_multiplication_output}')

Matrix Multiplication of
[[1 2 3]
 [4 5 6]
 [7 8 9]]

and
[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]

is:-
[[12 12 12 12]
 [30 30 30 30]
 [48 48 48 48]]


In [ ]:
'''
As expected:-
First Row in Output = 2*1 + 2*2 + 2*3 = 12
Second Row in Output = 2*4 + 2*5 + 2*6 = 30
Similarly, the third row!
'''

**Q4)**

Create elementwise multiplication for the first 2D array created in Q3 of shape 3x3 with the 2D array of random integers of shape 3x3 in Q2. You can achieve this with `*` operator.

In [ ]:
element_wise_multiplication = arr_2d * rand_int_arr
print(f'Elementwise Multiplication of\n{arr_2d}\n\nwith\n{rand_int_arr}\n\nis:-\n{element_wise_multiplication}')

Elementwise Multiplication of
[[1 2 3]
 [4 5 6]
 [7 8 9]]

with
[[ 6  3 10]
 [ 7  4  6]
 [ 9  2  6]]

is:-
[[ 6  6 30]
 [28 20 36]
 [63 16 54]]


In [ ]:
'''
Here, the elements are mapped onto each other and then performs multiplication.
Hence, on index (0,0) we have 1x6 = 6
On index, (1,1) we have 5x4 = 20
So on and so forth!
'''