# <center> W2S3 | Python - III

---

**In this Session:-**       
1. Loop with Condition
2. List Comprehension
3. Functions
4. Object-Oriented Programming
5. NumPy
6. Matplotlib
7. Practice Questions for you

### 1. Loop with Condition

In [ ]:
# Guess the output of this code
for index in range(0, 10):
    print(index)
    if index == 3:
        break # Breaks the loop if the condition is met

0
1
2
3


In [ ]:
# Can you guess what's happening here and which loop will break?
for x in range(5): # x = 0, 1
    for y in range(5): # y =0, y = 1 --> (0, 0), (0, 1), (1, 0), (1, 1)
        if y > 2:
            break
        print(f"({x},{y})")

(0,0)
(0,1)
(0,2)
(1,0)
(1,1)
(1,2)
(2,0)
(2,1)
(2,2)
(3,0)
(3,1)
(3,2)
(4,0)
(4,1)
(4,2)


In [ ]:
# Using break with while loop
print('-- Help: type quit to exit --')
while True:
    color = input('Enter your favorite color:')
    # Alternate way to terminate the while loop will be:- use color.upper() == 'QUIT'
    if color.lower() == 'quit':
        break

-- Help: type quit to exit --
Enter your favorite color:quit


In [ ]:
# Create a tuple to store all the planets in our solar system
planets = ("Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune")

# Your mission is to find if any gas giant is present in the planets tuple. If found even one, terminate the search
gas_giants = ('Jupiter', 'Saturn', 'Uranus', 'Neptune')

for planet in planets:
  if planet.title() in gas_giants:
    print(f'Found one Gas Giant - {planet.title()}. Mission accomplished!')
    break
else:
  print(f'All the plantes are explored. No Gas Giants found in the Mission!')

Found one Gas Giant - Jupiter. Mission accomplished!


### 2. List Comprehension

In [ ]:
# Create a string
str_var = '123456789'

# Store charachter of this string as an integer element of a list called char_list if it is more than 5
char_list = []

for ch in str_var:
  if int(ch) > 5:
    char_list.append(int(ch))

# Print the char_list
print(char_list)

[6, 7, 8, 9]


In [ ]:
# List comprehension to do the same task
char_list = [int(ch) for ch in str_var if int(ch) > 5] # [<element to append in list> <for condition> <if condition>]
print(char_list)

[6, 7, 8, 9]


### 3. Functions

In [ ]:
# Define a function to greet with no parameters
def greet():
  print('Hello!')

In [ ]:
# Call the function
greet()

Hello!


In [ ]:
# Define the same function but now with name argument
def greet(name):
  print(f'Hey, {name.title()}!')

In [ ]:
# Call the function
greet('rohan shah')

Hey, Rohan Shah!


In [ ]:
# Function with positional arguments (order matters)
def greet(name, msg):
  print(f"Hey {name.title()}! {msg}")

In [ ]:
# Call the function
greet('Rohan Shah', 'Welcome to week 2 of AI4LR')
greet('Welcome to week 2 of AI4LR', 'Rohan Shah') # Position matters!

Hey Rohan Shah! Welcome to week 2 of AI4LR
Hey Welcome To Week 2 Of Ai4Lr! Rohan Shah


In [ ]:
# Calling function via keyword arguments, this way order won't matter
greet(msg='Welcome to week 2 of AI4LR', name='Rohan Shah')

Hey Rohan Shah! Welcome to week 2 of AI4LR


In [ ]:
# Default arguments while building a function
def greet(name, msg = 'Hello'):
  print(f'{msg}, {name.title()}!')

In [ ]:
greet('Rohan')

Hello, Rohan!


In [ ]:
# Call the function with/without msg arg but also keep in mind the order whenever mixing the different arguments
'''
Find Imposter (error code) amongst this:-
'''
greet('Rohan')
greet('Rohan', 'Hi')
#greet(msg='Helluuuuuu', 'Rohan')
greet(msg='Heya', name='Rohan')
greet('Rohan', msg='Heeyyy')

print()

Hello, Rohan!
Hi, Rohan!
Heya, Rohan!
Heeyyy, Rohan!



* Combining these concepts, you can have functions with a mix of positional, keyword, and default arguments.
* When defining such a function, positional arguments must come before keyword arguments.
* As the order matters in positional arguments.


In [ ]:
# Positional args --> Key Word arguments
def example_function(arg1, arg2, kwarg1="default_value", kwarg2="another_default"):
    pass

In [ ]:
# Recursive Function
def count_down(start_countdown_val, first_call=True):
  if first_call == True:
    print('Launching our Rocket in:-\n')
  print(start_countdown_val)
  next_val = start_countdown_val - 1
  if next_val > 0:
    count_down(next_val, False)
  else:
    print('\nLift Off Begins!')

In [ ]:
count_down(10)

Launching our Rocket in:-

10
9
8
7
6
5
4
3
2
1

Lift Off Begins!


### 4. Object-Orient Programming

**Adding step by step addition of new parts of a class to build a full class**

In [ ]:
# Create a class
class Rocket():
  pass

In [ ]:
# Building a Constructor that tells about the current location of Rocket
class Rocket():
    # Constructor --> What all goes in the Rocket class
    def __init__(self):
        # Each rocket has an (x,y) position.
        self.x = 0
        self.y = 0

In [ ]:
# Adding a simple method that allows rocket to move up by one unit
class Rocket():
    # Constructor
    def __init__(self):
        # Each rocket has an (x,y) position.
        # You can also call them as attributes --> they work like variables for this class Rocket
        self.x = 0
        self.y = 0

    # Method to move up
    def move_up(self):
        # Increment the y-position of the rocket.
        self.y += 1 # self.y = self.y + 1

In [ ]:
# Create a Rocket object, and have it start to move up.
my_rocket = Rocket()
print("Rocket altitude:", my_rocket.y)

my_rocket.move_up()
print("Rocket altitude:", my_rocket.y)

my_rocket.move_up()
print("Rocket altitude:", my_rocket.y)

Rocket altitude: 0
Rocket altitude: 1
Rocket altitude: 2


In [ ]:
my_rockets = []
for x in range(0,5):
    new_rocket = Rocket()
    my_rockets.append(new_rocket)

In [ ]:
# Create a fleet of 5 rockets, and store them in a list.
my_rockets = []
for x in range(0,5):
    new_rocket = Rocket()
    my_rockets.append(new_rocket)

# Show that each rocket is a separate object and only first rocket moves up
my_rockets[1].move_up()
my_rockets[0].move_up()
my_rockets[0].move_up()
for idx, rocket in enumerate(my_rockets):
    print(f'Rocket {idx+1} -->\n{rocket}')
    print(f'Moved up by {rocket.y} units')
    print()

Rocket 1 -->
Moved up by 2 units

Rocket 2 -->
Moved up by 1 units

Rocket 3 -->
Moved up by 0 units

Rocket 4 -->
Moved up by 0 units

Rocket 5 -->
Moved up by 0 units



In [ ]:
'''Adding more functionality to the Rocket'''
class Rocket():
    # Constructor Update
    def __init__(self, x=0, y=0):
        # Each rocket has an (x,y) position.
        self.x = x
        self.y = y
    # Move method Update
    def move_rocket(self, x_increment=0, y_increment=1):
        # Move the rocket according to the paremeters given.
        #  Default behavior is to move the rocket up one unit.
        self.x += x_increment
        self.y += y_increment

In [ ]:
# Create three rockets.
rockets = [Rocket() for x in range(0,3)]

# Move each rocket a different amount.
rockets[0].move_rocket()
rockets[1].move_rocket(10,10)
rockets[2].move_rocket(-10,0)

# Show where each rocket is.
for index, rocket in enumerate(rockets):
    print("Rocket %d is at (%d, %d)." % (index+1, rocket.x, rocket.y))

Rocket 1 is at (0, 1).
Rocket 2 is at (10, 10).
Rocket 3 is at (-10, 0).


In [ ]:
# shortest distance between two points (x1, y1), (x2, y2)

#sqrt((x2-x1)**2 + (y2-y1)**2)



''''
              X
              |
              |
X-------------
'''

In [ ]:
'''Adding one more method'''
from math import sqrt

class Rocket():
    # Rocket simulates a rocket ship for a game,
    #  or a physics simulation.

    def __init__(self, x=0, y=0):
        # Each rocket has an (x,y) position.
        self.x = x
        self.y = y

    def move_rocket(self, x_increment=0, y_increment=1):
        # Move the rocket according to the paremeters given.
        #  Default behavior is to move the rocket up one unit.
        self.x += x_increment
        self.y += y_increment

    def get_distance(self, other_rocket):
        # Calculates the distance from this rocket to another rocket,
        #  and returns that value.
        distance = sqrt((self.x-other_rocket.x)**2+(self.y-other_rocket.y)**2)
        return distance

In [ ]:
# Make two rockets, at different places.
rocket_0 = Rocket()
rocket_1 = Rocket(10,5)

# Show the distance between them.
distance = rocket_0.get_distance(rocket_1)
print(f"The rockets are {distance} units apart.")

The rockets are 11.180339887498949 units apart.


### 5. NumPy

In [ ]:
# Importing the library
import numpy as np

In [ ]:
# Create an array
my_array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)

# Print it out to see how it looks like
print(my_array)

In [ ]:
'''Multiple ways of creating numpy arrays'''

# Array of ones
a = np.ones((3, 4))          # Creates an array full of 1s of size 3x4

# Array of zeros
b = np.zeros((2, 3, 4))      # Creates an array full of 0s of size 2x3x4

# Array of random values
c = np.random.random((2, 2)) # Creates an array of random values of size 2x2

# Array of constant values
d = np.full((2, 2), 7)       # Creates an array of constant values of size 2x2

# Array of evenly spaced values
e = np.arange(10, 25, 4)     # Creates an array starting from 10 (inclusive) till 25 (exclusive) after every 4 values

# Array of equally spaced items
f = np.linspace(10, 25, 4)   # Creates an array of 4 elements with equal spaces in between them including the last value!

In [ ]:
'''Print it all out'''
for ele in [a, b, c, d, e, f]:
  print(f"{ele}\n\n----------------------------\n")

In [ ]:
'''For the above array a, print its dimensions, size and shape'''

print(f"Dimensions of array a = {a.ndim}")  # Dimensions of the array
print(f"Size of array a = {a.size}")        # Total elements inside the array
print(f"Shape of array a = {a.shape}")      # Shape of array in the form of rows x cols

In [ ]:
# You can also reshape the arrays - reshape array a to 1x12
a = a.reshape(1,12)
print(a, a.shape)

In [ ]:
# Finding minimum, maximum, sum, and mean an array c
print(f'Minimum value of y = {c.min()}')
print(f'Maximum value of y = {c.max()}')
print(f'Sum of y = {c.sum()}')
print(f'Mean of y = {c.mean()}')

**Q)**
- *Create a 2D array as shown below:-*       
  [[1 2 3 4]          
 [5 6 7 8]]

- *Create a 3D array of random integers using np.random.randint(min_val, max_val, size)*       
  Use min val = 1, max val = 100, size = (5,2,4)

- *print both the arrays*

In [ ]:
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8]])

'''Something new!!'''
np.random.seed(42) # Seed generates same set of random numbers each time we run it as it will be used later in this notebook we want it to genrate same 3D array always when we run it

arr_3d = np.random.randint(low=1, high=100, (5,2,4))

print(f"2D array:-\n{arr_2d}\n\n3D array:-\n{arr_3d}")

In [ ]:
'''Remember indexing starts with 0 in python!'''

# Select the element at row 1 column 2 from 2D array
print(arr_2d[1][2])

# Select the element at row 1 column 2 from 2D array
print(arr_2d[1, 2])

# Select the element at row 1, column 2 from the 0th bunch from 3D array
print(arr_3d[0, 1, 2])

In [ ]:
# Let us now slice the 2D and 3D arrays

'''
Grab the following numbers from 2D array:-
[[1 2]
[5 6]]
'''

# That is in 0th row and 1st row we need first 2 cols
arr_2d[:, :2] # arr[row, cols] ---> note that : means everyhting and :2 means everything before 2nd element, 2: everything from 2nd element till the end

In [ ]:
'''
Grab the following numbers from 3D array:-
[[88 38]
[64 21]]
'''

# From the 2nd bunch we need both the rows and alternate columns
arr_3d[2, :, 0:4:2] # here we are using the start(inclusive):end(exclusive):skip notation to get the required output

## Very important concept of numpy ---> axis
<img src = 'https://www.sharpsightlabs.com/wp-content/uploads/2018/12/numpy-arrays-have-axes_updated_v2.png' width = 55%>

In [ ]:
'''
Create the following array using numpy techniques:-
[[10 20 30 40]
[50 60 70 80]
[90 100 110 120]]
'''

arr = np.arange(10, 121, 10).reshape(3, 4)
print(arr)

In [ ]:
print(arr.sum(axis = 1)) # Sums up the rows
print(arr.sum(axis = 0)) # Sums up the cols

### Practice Questions for you

#### **Q1) What is the output of the given Python code snippet when executed?**

```
odd_numbers = (1, 3, 5)
even_numbers = (2, 4, 6)
numbers = (*odd_numbers, *even_numbers)
print(numbers)
```

Explain your logic by adding comments to every line!






#### **Soln 1:-**

In [ ]:
# Write your solution here





In [ ]:
# Soln 1
odd_numbers = (1, 3, 5)                    # Creates a tuple of odd numbers
even_numbers = (2, 4, 6)                   # Creates a tuple of even numbers
numbers = (*odd_numbers, *even_numbers)    # Unpacks the odd number and even numbers to create number tuple
print(numbers)                             # Prints the output

#### **Q2) Space Company Question**

A space company is planning a series of rocket launches. Each rocket launch is represented by a positive integer, where the value represents the payload weight in kilograms. The company has a policy that a rocket can only be launched if its payload weight is less than or equal to a specified maximum limit.

Write a recursive function **launch_rocket** that takes a list of payload weights and a maximum weight limit as parameters. The function should determine whether each rocket in the list can be launched or not based on the weight limit. The function should return a list of boolean values, where each value represents whether the corresponding rocket can be launched (True) or not (False).

For example,
```
payload_weights = [1200, 800, 1500, 600, 1000]
max_limit = 1000
result = launch_rocket(payload_weights, max_limit)
print(result)
```

Output should be,
```
[False, True, False, True, True]
```

In [ ]:
# Write your solution here






In [ ]:
# Soln 2 - Shorter method using list comprehension
def launch_rocket(payload_weights, max_limit):
    '''
    Argumetns ~
    1) payload_weights - list of payload_weights
    2) max_limit - float value indicating the maximum weight a rocket can have for a launch

    Returns ~
    1) list
    '''

    # <do this> <if this condition is true> <else do that> <for condition> --> List comprehension with if and else
    return [True if weight <= max_limit else False for weight in payload_weights]

In [ ]:
# Alternate approach - Long method using append
def launch_rocket_alternative(payload_weights, max_limit):
  '''
  Argumetns ~
  1) payload_weights - list of payload_weights
  2) max_limit - float value indicating the maximum weight a rocket can have for a launch

  Returns ~
  1) list of True or False depending on if rocket should be launched
  '''

  # Create empty list to store the output of True or False
  will_launch = []

  # For every weight value in payload_weights list
  for weight in payload_weights:
    if weight <= max_limit:     # If the weight value is below or equal to max_limit
      will_launch.append(True)  # Add True to will_launch list
    else:                       # Else
      will_launch.append(False) # Add False to will_launch list
  return will_launch            # Return the full list after for loop is completed

In [ ]:
# Method 1 using list comprehension
launch_rocket([1200, 800, 1500, 600, 1000], 1000)

[False, True, False, True, True]

In [ ]:
# Method 2 - Using append
launch_rocket_alternative([1200, 800, 1500, 600, 1000], 1000)

[False, True, False, True, True]

**Q3) Stellar Classificiation**

In astronomy, stars are classified based on their spectral characteristics. The spectral type is often represented by a single letter (O, B, A, F, G, K, M), where O-type stars are the hottest, and M-type stars are the coolest.

Write a Python function that classifies a star based on its temperature, given in Kelvin. The temperature ranges for each spectral type are as follows:

* O:- $T \geq 30,000 K$
* B:- $10,000K \leq T < 30,000K$
* A:- $7,500K \leq T < 10,000K$
* F:- $6,000K \leq T < 7,500K$
* G:- $5,000K \leq T < 6,000K$
* K:- $3,500K \leq T < 5,000K$
* M:- $T < 3,500K$

Your function should take the temperature as input and return the corresponding spectral type.

This is what you have to run on the **classify_star()** function:-
```
temperature = 8000.0  # temperature in Kelvin
spectral_type = classify_star(temperature)
print(f"The star is of spectral type:- {spectral_type}")
```

In [ ]:
# Write your solution here






In [ ]:
# Soln 3
def classify_star(temperature):
    '''
    Arguments ~
    1) temperature - Value of star's temperature in Kelvin(float)

    Returns ~
    1) Spectral Type wrt to the input temperature
    '''

    # Define spectral_types dictionary with keys being spectra and values being range of temp values
    spectral_types = {
        'O': (30000, float('inf')), # float('inf') is one of the ways to indicate positive infinity
        'B': (10000, 30000),
        'A': (7500, 10000),
        'F': (6000, 7500),
        'G': (5000, 6000),
        'K': (3500, 5000),
        'M': (float('-inf'), 3500), # Similarly, float('-inf') is used to denote negative infinity
    }

    # Loop through dictionary items
    for spectral_type, (lower, upper) in spectral_types.items(): # Value of dict is tuple, remember that!
        if lower <= temperature < upper: # Condition for spectra
            return spectral_type         # Return the spectral_type if condition is true

In [ ]:
temperature = 8000.0  # temperature in Kelvin
spectral_type = classify_star(temperature)
print(f"The star is of spectral type:- {spectral_type}")

The star is of spectral type:- A


**Q4) Factorial Calculator**


Write a recursive function **calculate_factorial** to calculate the factorial of a non-negative integer `n`.

For example, 5 factorial is:-          
```
5! = 5 x 4 x 3 x 2 x 1 = 120
```
The function should return -1 in case of any non positive integer input

In [ ]:
# Write your solution here





In [ ]:
def factorial(num):
  '''
  Arguments ~
  1) num - Positive integer

  Returns ~
  2) -1 if input is a non positive integer or returns factorial of the num
  '''
  '''
  3 x 2 x 1
  '''

  # Base case
  if num == 1 or num == 0:
      return 1
  # If num is a positive integer
  elif num > 1 and isinstance(num, int): # isinstance(element, type) is used to check the data type of element
      return num * factorial(num - 1)        # Recursion being used here
  # If num is a non-positive integer
  else:
    return -1

In [ ]:
# Call the factorial of 5
factorial(5)

120

---
# <center> THE END