# W2S3 | Python - III
---

**In this Session:-**
1. Control Flow
2. Functions
3. NumPy

### Loop

In [1]:
# Range





In [ ]:
# For loop with range to print numbers between 1 to 10




In [ ]:
# While loop to print the numbers between 1 to 10



In [5]:
# Looping through a List of celestial bodies and printing each element
celestial_bodies = ['Black Hole', 'Exoplanets', 'Neutron Star']

for body in celestial_bodies:
    print(body)


Black Hole
Exoplanets
Neutron Star


In [7]:
# Create a for loop that takes the celestial_bodies list and converts its elements to uppercase strings

for i in range(len(celestial_bodies)):
   celestial_bodies[i] = celestial_bodies[i].upper()

print(celestial_bodies) 


['BLACK HOLE', 'EXOPLANETS', 'NEUTRON STAR']


In [8]:
# Alternate way to deal with this problem would be using enumerate

for i, body in enumerate(celestial_bodies):
    celestial_bodies[i] = body.lower()
print(celestial_bodies)

['black hole', 'exoplanets', 'neutron star']


In [9]:
# Try out yourself, whatshould be the code to convert the items of celestial_bodies to lowercase?


# Alternate way to deal with this problem would be using enumerate

for i, body in enumerate(celestial_bodies):
    celestial_bodies[i] = body.lower()
print(celestial_bodies)


['black hole', 'exoplanets', 'neutron star']


In [12]:
# Looping through tuple is similar to list, here is how you can loop through a dictionary
inner_planet_moons = {'Mercury' : 0,
                      'Venus' : 0,
                      'Mars' : 2,
                      'Earth' : 1}

print(inner_planet_moons.items())

for key, values in inner_planet_moons.items():
    print(key,":", values)

dict_items([('Mercury', 0), ('Venus', 0), ('Mars', 2), ('Earth', 1)])
Mercury : 0
Venus : 0
Mars : 2
Earth : 1


### Loop with Conditions

In [13]:
# Create two variables to compare using if-elif-else block
a = 5
b = 2

# Check if a > b, a<b or a==b using
if a > b:                # If this is true
  print(f'{a} > {b}')    # Print this
elif a < b:              # Else if the above condition is not true, this is true
  print(f'{a} < {b}')    # Then print this
else:                    # If none of the above conditions are true
  print(f'{a} == {b}')   # Then print this

5 > 2


In [14]:
# Guess the output of this code
for index in range(0, 10):
    print(index)
    if index == 3:
        break

0
1
2
3


In [16]:
# Can you guess the output of this code?
ct = 0
print('-- Help: type quit to exit --')
while True:
    ct+=1
    color = input(f'Enter your favorite celestial body {ct}:- ')
    # Can you think of an alternate way to terminate the while loop? (very similar)
    if color.lower() == 'quit':
        break

-- Help: type quit to exit --


KeyboardInterrupt: Interrupted by user

In [25]:
# Create a tuple to store all the planets in our solar system
planets = ("Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune")

# Your mission is to find if any gas giant is present in the planets tuple. If found even one, terminate the search
gas_giants = ('Jupiter', 'Saturn', 'Uranus', 'Neptune')

if any(planet.title() in gas_giants for planet in planets):
  print(f'Found one Gas Giant - {planet.title()}. Mission accomplished!')
else:
  print('All the planets are explored. No Gas Giants found in the mission!')


Found one Gas Giant - Mercury. Mission accomplished!


### List Comprehension

In [26]:
''' CODE WITHOUT LIST COMPREHENSION '''

# Create a string
str_var = '123456789'

# Store charachter of this string as an integer element of a list called char_list if it is more than 5
char_list = []

for ch in str_var:
  if int(ch) > 5:
    char_list.append(int(ch))

# Print the char_list
print(char_list)

[6, 7, 8, 9]


In [30]:
''' CODE WITH LIST COMPREHENSION '''
print([int(ch) for ch in str_var if int(ch) > 5])

# list comprehension with if-else
# [do this if this is true else do this for item in list]

[6, 7, 8, 9]


### Functions

In [34]:
# Create a function to greet everyone in the session

def greet(name):
    return f'Hello {name}!' 



In [35]:
# Call the function

# Create a list of names
names = ['Amit', 'Raj', 'Suresh', 'Ramesh']
greet(names)


"Hello ['Amit', 'Raj', 'Suresh', 'Ramesh']!"

In [37]:
def greet_person(name, message):
    return f"Hello {name}! {message}"




In [38]:
# Call the function
greet_person('Rohan Shah', 'Welcome to week 2 of ADS') # What will be the output
#func_name('Welcome to week 2 of ADS', 'Rohan Shah') # What will be the output?

'Hello Rohan Shah! Welcome to week 2 of ADS'

In [ ]:
# Default arguments while building a function
def greet(name, msg = 'Hello'):
  print(f'{msg}, {name.title()}!')

In [ ]:
greet('Rohan')

In [39]:
'''
Find Imposter (error code) amongst this:-
'''
#greet('Rohan')
#greet('Rohan', 'Hi')
#greet(msg='Helluuuuuu', 'Rohan')
#greet(msg='Heya', name='Rohan')
#greet('Rohan', msg='Heeyyy')

print("#greet(msg='Helluuuuuu', 'Rohan')")

#greet(msg='Helluuuuuu', 'Rohan')


### NumPy (Numerical Python Library)

In [40]:
# Import Library to use it
import numpy as np

In [45]:
# Create an array of [[1,2,3,4], [5,6,7,8]] with 8-bit integer datatype
a=np.array([[1.2,2,3,4], [5,6,7,8]], dtype=np.int8)

a[0][0].dtype



dtype('int8')

In [53]:
'''Multiple ways of creating numpy arrays'''

# Array of ones
a = np.ones((3, 4))          # Creates an array full of 1s of size 3x4

# Array of zeros
b = np.zeros((2, 3, 4))      # Creates an array full of 0s of size 2x3x4

# Array of random values
c = np.random.random((2, 2)) # Creates an array of random values of size 2x2

# Array of constant values
d = np.full((2, 2), 7)       # Creates an array of constant values of size 2x2

# Array of evenly spaced values
e = np.arange(10, 25, 4)     # Creates an array starting from 10 (inclusive) till 25 (exclusive) after every 4 values

# Array of equally spaced items
f = np.linspace(10, 25, 4)   # Creates an array of 4 elements with equal spaces in between them including the last value!

In [47]:
# Print all the abcdef using a for loop
for array in [a, b, c, d, e, f]:
    print(array)
    print('-----------------')



[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
-----------------
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
-----------------
[[0.96763534 0.43736214]
 [0.39267384 0.85618791]]
-----------------
[[7 7]
 [7 7]]
-----------------
[10 14 18 22]
-----------------
[10. 15. 20. 25.]
-----------------


In [54]:
'''For the above array a, print its dimensions, size and shape'''

print(f"Dimensions of array a = {a.ndim}")  # Dimensions of the array
print(f"Size of array a = {a.size}")        # Total elements inside the array
print(f"Shape of array a = {a.shape}")      # Shape of array in the form of rows x cols

Dimensions of array a = 2
Size of array a = 12
Shape of array a = (3, 4)


In [55]:
# You can also reshape the arrays - reshape array a to 1x12
a = a.reshape(1,12)
print(a, a.shape)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]] (1, 12)


In [56]:
# Finding minimum, maximum, sum, and mean an array c
print(f'Minimum value of y = {c.min()}')
print(f'Maximum value of y = {c.max()}')
print(f'Sum of y = {c.sum()}')
print(f'Mean of y = {c.mean()}')

Minimum value of y = 0.020169603354016963
Maximum value of y = 0.63971670040035
Sum of y = 1.4734539907416093
Mean of y = 0.36836349768540233


In [57]:
# Creating a 2D array
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8]])

'''Something new!!'''
np.random.seed(42) # Seed generates same set of random numbers each time we run it as it will be used later in this notebook we want it to genrate same 3D array always when we run it

arr_3d = np.random.randint(low=1, high=100, size=(5,2,4))

print(f"2D array:-\n{arr_2d}\n\n3D array:-\n{arr_3d}")

2D array:-
[[1 2 3 4]
 [5 6 7 8]]

3D array:-
[[[52 93 15 72]
  [61 21 83 87]]

 [[75 75 88 24]
  [ 3 22 53  2]]

 [[88 30 38  2]
  [64 60 21 33]]

 [[76 58 22 89]
  [49 91 59 42]]

 [[92 60 80 15]
  [62 62 47 62]]]


In [58]:
'''Remember indexing starts with 0 in python!'''

# Select the element at row 1 column 2 from 2D array
print(arr_2d[1][2])

# Select the element at row 1 column 2 from 2D array
print(arr_2d[1, 2])

# Select the element at row 1, column 2 from the 0th bunch from 3D array
print(arr_3d[0, 1, 2])

7
7
83


In [59]:
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [61]:
'''
Grab the following numbers from 2D array:-
[[1 2]
[5 6]]
'''

print(arr_2d[0:2,0:2])

[[1 2]
 [5 6]]


In [ ]:
print(arr_3d)

In [66]:
'''
Grab the following numbers from 3D array:-
[[88 38]
[64 21]]
'''
print(arr_3d[2,:,0:3:2])

[[88 38]
 [64 21]]


#### Very important concept of numpy ---> axis
<img src = 'https://www.sharpsightlabs.com/wp-content/uploads/2018/12/numpy-arrays-have-axes_updated_v2.png' width = 55%>

In [ ]:
'''
Create the following array using numpy techniques:-
[[10 20 30 40] #100
[50 60 70 80]   #200
[90 100 110 120]]  #300
'''
#150 #180 #210 #240

arr =

In [ ]:
print(arr.sum(axis = 1)) # Sums up the rows
print(arr.sum(axis = 0)) # Sums up the cols

In [68]:
arr_3d.sum(axis=1)

array([[113, 114,  98, 159],
       [ 78,  97, 141,  26],
       [152,  90,  59,  35],
       [125, 149,  81, 131],
       [154, 122, 127,  77]])